//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------


using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using OslerAlumni.Core.Kentico.Models;

[assembly: RegisterCustomTable(CustomTable_DevelopmentResourceTypeItem.CLASS_NAME, typeof(CustomTable_DevelopmentResourceTypeItem))]

namespace OslerAlumni.Core.Kentico.Models
{
    /// <summary>
	/// Represents a content item of type CustomTable_DevelopmentResourceTypeItem.
	/// </summary>
	public partial class CustomTable_DevelopmentResourceTypeItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.CustomTable_DevelopmentResourceType";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_DevelopmentResourceTypeItem fields.
        /// </summary>
        private readonly CustomTable_DevelopmentResourceTypeItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Display Name.
        /// </summary>
        [DatabaseField]
        public string DisplayName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DisplayName"), @"");
            }
            set
            {
                SetValue("DisplayName", value);
            }
        }


        /// <summary>
        /// Code Name.
        /// </summary>
        [DatabaseField]
        public string CodeName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CodeName"), @"");
            }
            set
            {
                SetValue("CodeName", value);
            }
        }


        /// <summary>
        /// Enabled.
        /// </summary>
        [DatabaseField]
        public bool Enabled
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Enabled"), true);
            }
            set
            {
                SetValue("Enabled", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_DevelopmentResourceTypeItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_DevelopmentResourceTypeItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_DevelopmentResourceTypeItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CustomTable_DevelopmentResourceTypeItemFields : AbstractHierarchicalObject<CustomTable_DevelopmentResourceTypeItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_DevelopmentResourceTypeItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_DevelopmentResourceTypeItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_DevelopmentResourceTypeItemFields" /> class with the specified content item of type CustomTable_DevelopmentResourceTypeItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_DevelopmentResourceTypeItem that is a target of the extended API.</param>
            public CustomTable_DevelopmentResourceTypeItemFields(CustomTable_DevelopmentResourceTypeItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Display Name.
            /// </summary>
            public string DisplayName
            {
                get
                {
                    return mInstance.DisplayName;
                }
                set
                {
                    mInstance.DisplayName = value;
                }
            }


            /// <summary>
            /// Code Name.
            /// </summary>
            public string CodeName
            {
                get
                {
                    return mInstance.CodeName;
                }
                set
                {
                    mInstance.CodeName = value;
                }
            }


            /// <summary>
            /// Enabled.
            /// </summary>
            public bool Enabled
            {
                get
                {
                    return mInstance.Enabled;
                }
                set
                {
                    mInstance.Enabled = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_DevelopmentResourceTypeItem" /> class.
        /// </summary>
        public CustomTable_DevelopmentResourceTypeItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_DevelopmentResourceTypeItemFields(this);
        }

        #endregion
    }
}
