//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using CMS.DocumentEngine;
using OslerAlumni.Core.Definitions;
using OslerAlumni.Core.Kentico.Models;


[assembly: RegisterDocumentType(OslerAlumni.Core.Kentico.Models.PageType_Event.CLASS_NAME, typeof(PageType_Event))]

namespace OslerAlumni.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Event.
    /// </summary>
    public partial class PageType_Event : IBasePageType, ICompetitorProtected
    {
        public DeliveryMethods DeliveryMethodsEnum =>
            (DeliveryMethods) Enum.Parse(typeof(DeliveryMethods), DeliveryMethods);
    }
}
