//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using OslerAlumni.Core.Kentico.Models;

[assembly: RegisterDocumentType(PageType_LandingPage.CLASS_NAME, typeof(PageType_LandingPage))]

namespace OslerAlumni.Core.Kentico.Models
{
    /// <summary>
	/// Represents a content item of type PageType_LandingPage.
	/// </summary>
	public partial class PageType_LandingPage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_LandingPage";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_LandingPage fields.
        /// </summary>
        private readonly PageType_LandingPageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_PageID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_LandingPageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_LandingPageID"), 0);
            }
            set
            {
                SetValue("PageType_LandingPageID", value);
            }
        }


        /// <summary>
        /// Name of the item in the content tree.
        /// </summary>
        [DatabaseField]
        public string PageName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageName"), @"");
            }
            set
            {
                SetValue("PageName", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Short Description.
        /// </summary>
        [DatabaseField]
        public string ShortDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ShortDescription"), @"");
            }
            set
            {
                SetValue("ShortDescription", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Number of items to be displayed per page in the main listing.
        /// </summary>
        [DatabaseField]
        public int MainListPageSize
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("MainListPageSize"), 10);
            }
            set
            {
                SetValue("MainListPageSize", value);
            }
        }


        /// <summary>
        /// Number of items to be displayed per page in the top listing, if supported by this landing page.
        /// </summary>
        [DatabaseField]
        public int TopListPageSize
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TopListPageSize"), 0);
            }
            set
            {
                SetValue("TopListPageSize", value);
            }
        }


        /// <summary>
        /// Default Image - Featured Item.
        /// </summary>
        [DatabaseField]
        public string DefaultFeaturedImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultFeaturedImage"), @"");
            }
            set
            {
                SetValue("DefaultFeaturedImage", value);
            }
        }


        /// <summary>
        /// When enabled, prevent site visitors from navigating to the page directly.
        /// If the page has any URLs associated with it, they will be removed.
        /// </summary>
        [DatabaseField]
        public bool DocumentMenuItemHideInNavigation1
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DocumentMenuItemHideInNavigation"), false);
            }
            set
            {
                SetValue("DocumentMenuItemHideInNavigation", value);
            }
        }


        /// <summary>
        /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultController
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultController"), @"");
            }
            set
            {
                SetValue("DefaultController", value);
            }
        }


        /// <summary>
        /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultAction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultAction"), @"");
            }
            set
            {
                SetValue("DefaultAction", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_LandingPage fields.
        /// </summary>
        [RegisterProperty]
        public PageType_LandingPageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_LandingPage fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_LandingPageFields : AbstractHierarchicalObject<PageType_LandingPageFields>
        {
            /// <summary>
            /// The content item of type PageType_LandingPage that is a target of the extended API.
            /// </summary>
            private readonly PageType_LandingPage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_LandingPageFields" /> class with the specified content item of type PageType_LandingPage.
            /// </summary>
            /// <param name="instance">The content item of type PageType_LandingPage that is a target of the extended API.</param>
            public PageType_LandingPageFields(PageType_LandingPage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_PageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_LandingPageID;
                }
                set
                {
                    mInstance.PageType_LandingPageID = value;
                }
            }


            /// <summary>
            /// Name of the item in the content tree.
            /// </summary>
            public string PageName
            {
                get
                {
                    return mInstance.PageName;
                }
                set
                {
                    mInstance.PageName = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Short Description.
            /// </summary>
            public string ShortDescription
            {
                get
                {
                    return mInstance.ShortDescription;
                }
                set
                {
                    mInstance.ShortDescription = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Number of items to be displayed per page in the main listing.
            /// </summary>
            public int MainListPageSize
            {
                get
                {
                    return mInstance.MainListPageSize;
                }
                set
                {
                    mInstance.MainListPageSize = value;
                }
            }


            /// <summary>
            /// Number of items to be displayed per page in the top listing, if supported by this landing page.
            /// </summary>
            public int TopListPageSize
            {
                get
                {
                    return mInstance.TopListPageSize;
                }
                set
                {
                    mInstance.TopListPageSize = value;
                }
            }


            /// <summary>
            /// Featured Items.
            /// </summary>
            public IEnumerable<TreeNode> FeaturedItems
            {
                get
                {
                    return mInstance.GetRelatedDocuments("FeaturedItems");
                }
            }


            /// <summary>
            /// Default Image - Featured Item.
            /// </summary>
            public string DefaultFeaturedImage
            {
                get
                {
                    return mInstance.DefaultFeaturedImage;
                }
                set
                {
                    mInstance.DefaultFeaturedImage = value;
                }
            }


            /// <summary>
            /// CTAs that are to appear in the top widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> TopWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("TopWidgetZone");
                }
            }


            /// <summary>
            /// Related Content Widget Zone.
            /// </summary>
            public IEnumerable<TreeNode> RelatedContentWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("RelatedContentWidgetZone");
                }
            }


            /// <summary>
            /// When enabled, prevent site visitors from navigating to the page directly.
            /// If the page has any URLs associated with it, they will be removed.
            /// </summary>
            public bool DocumentMenuItemHideInNavigation
            {
                get
                {
                    return mInstance.DocumentMenuItemHideInNavigation1;
                }
                set
                {
                    mInstance.DocumentMenuItemHideInNavigation1 = value;
                }
            }


            /// <summary>
            /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultController
            {
                get
                {
                    return mInstance.DefaultController;
                }
                set
                {
                    mInstance.DefaultController = value;
                }
            }


            /// <summary>
            /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultAction
            {
                get
                {
                    return mInstance.DefaultAction;
                }
                set
                {
                    mInstance.DefaultAction = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_LandingPage" /> class.
        /// </summary>
        public PageType_LandingPage() : base(CLASS_NAME)
        {
            mFields = new PageType_LandingPageFields(this);
        }

        #endregion
    }
}
