//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using OslerAlumni.Mvc.Core.Kentico.Models.Forms;


[assembly: RegisterBizForm(ContactUsItem.CLASS_NAME, typeof(ContactUsItem))]

namespace OslerAlumni.Mvc.Core.Kentico.Models.Forms
{

    /// <summary>
    /// Represents a content item of type ContactUsItem.
    /// </summary>
    public partial class ContactUsItem : BizFormItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BizForm.ContactUs";


        /// <summary>
        /// The instance of the class that provides extended API for working with ContactUsItem fields.
        /// </summary>
        private readonly ContactUsItemFields mFields;

        #endregion


        #region "Properties"


        /// <summary>
        /// OpportunityType.
        /// </summary>
        [DatabaseField]
        public string OpportunityType
        {
            get { return ValidationHelper.GetString(GetValue("OpportunityType"), @""); }
            set { SetValue("OpportunityType", value); }
        }

        /// <summary>
        /// ReasonForContactingUs.
        /// </summary>
        [DatabaseField]
        public string ReasonForContactingUs
        {
            get { return ValidationHelper.GetString(GetValue("ReasonForContactingUs"), @""); }
            set { SetValue("ReasonForContactingUs", value); }
        }


        /// <summary>
        /// UserName.
        /// </summary>
        [DatabaseField]
        public string UserName
        {
            get { return ValidationHelper.GetString(GetValue("UserName"), @""); }
            set { SetValue("UserName", value); }
        }





        /// <summary>
        /// FirstName.
        /// </summary>
        [DatabaseField]
        public string FirstName
        {
            get { return ValidationHelper.GetString(GetValue("FirstName"), @""); }
            set { SetValue("FirstName", value); }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string Email
        {
            get { return ValidationHelper.GetString(GetValue("Email"), @""); }
            set { SetValue("Email", value); }
        }


        /// <summary>
        /// PhoneNumber.
        /// </summary>
        [DatabaseField]
        public string PhoneNumber
        {
            get { return ValidationHelper.GetString(GetValue("PhoneNumber"), @""); }
            set { SetValue("PhoneNumber", value); }
        }


        /// <summary>
        /// Subject.
        /// </summary>
        [DatabaseField]
        public string Subject
        {
            get { return ValidationHelper.GetString(GetValue("Subject"), @""); }
            set { SetValue("Subject", value); }
        }


        /// <summary>
        /// Message.
        /// </summary>
        [DatabaseField]
        public string Message
        {
            get { return ValidationHelper.GetString(GetValue("Message"), @""); }
            set { SetValue("Message", value); }
        }


        /// <summary>
        /// LastName.
        /// </summary>
        [DatabaseField]
        public string LastName
        {
            get { return ValidationHelper.GetString(GetValue("LastName"), @""); }
            set { SetValue("LastName", value); }
        }


        /// <summary>
        /// CompanyName.
        /// </summary>
        [DatabaseField]
        public string CompanyName
        {
            get { return ValidationHelper.GetString(GetValue("CompanyName"), @""); }
            set { SetValue("CompanyName", value); }
        }


        /// <summary>
        /// Attachment.
        /// </summary>
        [DatabaseField]
        public string Attachment
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Attachment"), @"");
            }
            set
            {
                SetValue("Attachment", value);
            }
        }

        /// <summary>
        /// Gets an object that provides extended API for working with ContactUsItem fields.
        /// </summary>
        [RegisterProperty]
        public ContactUsItemFields Fields
        {
            get { return mFields; }
        }


        /// <summary>
        /// Provides extended API for working with ContactUsItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ContactUsItemFields : AbstractHierarchicalObject<ContactUsItemFields>
        {
            /// <summary>
            /// The content item of type ContactUsItem that is a target of the extended API.
            /// </summary>
            private readonly ContactUsItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactUsItemFields" /> class with the specified content item of type ContactUsItem.
            /// </summary>
            /// <param name="instance">The content item of type ContactUsItem that is a target of the extended API.</param>
            public ContactUsItemFields(ContactUsItem instance)
            {
                mInstance = instance;
            }

            /// <summary>
            /// OpportunityType.
            /// </summary>
            public string OpportunityType
            {
                get { return mInstance.OpportunityType; }
                set { mInstance.OpportunityType = value; }
            }


            /// <summary>
            /// ReasonForContactingUs.
            /// </summary>
            public string ReasonForContactingUs
            {
                get { return mInstance.ReasonForContactingUs; }
                set { mInstance.ReasonForContactingUs = value; }
            }


            /// <summary>
            /// UserName.
            /// </summary>
            public string UserName
            {
                get { return mInstance.UserName; }
                set { mInstance.UserName = value; }
            }


            /// <summary>
            /// UserGuid.
            /// </summary>
            public Guid UserGuid
            {
                get { return mInstance.UserGuid.Value; }
                set { mInstance.UserGuid = value; }
            }


            /// <summary>
            /// FirstName.
            /// </summary>
            public string FirstName
            {
                get { return mInstance.FirstName; }
                set { mInstance.FirstName = value; }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string Email
            {
                get { return mInstance.Email; }
                set { mInstance.Email = value; }
            }


            /// <summary>
            /// PhoneNumber.
            /// </summary>
            public string PhoneNumber
            {
                get { return mInstance.PhoneNumber; }
                set { mInstance.PhoneNumber = value; }
            }


            /// <summary>
            /// Subject.
            /// </summary>
            public string Subject
            {
                get { return mInstance.Subject; }
                set { mInstance.Subject = value; }
            }


            /// <summary>
            /// Message.
            /// </summary>
            public string Message
            {
                get { return mInstance.Message; }
                set { mInstance.Message = value; }
            }


            /// <summary>
            /// LastName.
            /// </summary>
            public string LastName
            {
                get { return mInstance.LastName; }
                set { mInstance.LastName = value; }
            }


            /// <summary>
            /// CompanyName.
            /// </summary>
            public string CompanyName
            {
                get { return mInstance.CompanyName; }
                set { mInstance.CompanyName = value; }
            }

            /// <summary>
            /// Attachment.
            /// </summary>
            public string Attachment
            {
                get
                {
                    return mInstance.Attachment;
                }
                set
                {
                    mInstance.Attachment = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactUsItem" /> class.
        /// </summary>
        public ContactUsItem() : base(CLASS_NAME)
        {
            mFields = new ContactUsItemFields(this);
        }

        #endregion
    }

}

