//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS;
using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Helpers;
using OslerAlumni.Mvc.Core.Kentico.Models;

[assembly: RegisterDocumentType(PageType_Home.CLASS_NAME, typeof(PageType_Home))]

namespace OslerAlumni.Mvc.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Home.
    /// </summary>
    public partial class PageType_Home : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_Home";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_Home fields.
        /// </summary>
        private readonly PageType_HomeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_HomePageID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_HomePageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_HomePageID"), 0);
            }
            set
            {
                SetValue("PageType_HomePageID", value);
            }
        }


        /// <summary>
        /// Name of the item in the content tree.
        /// </summary>
        [DatabaseField]
        public string PageName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageName"), @"");
            }
            set
            {
                SetValue("PageName", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Short Description.
        /// </summary>
        [DatabaseField]
        public string ShortDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ShortDescription"), @"");
            }
            set
            {
                SetValue("ShortDescription", value);
            }
        }


        /// <summary>
        /// Banner Header.
        /// </summary>
        [DatabaseField]
        public string BannerHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerHeader"), @"");
            }
            set
            {
                SetValue("BannerHeader", value);
            }
        }


        /// <summary>
        /// Banner Title.
        /// </summary>
        [DatabaseField]
        public string BannerTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerTitle"), @"");
            }
            set
            {
                SetValue("BannerTitle", value);
            }
        }


        /// <summary>
        /// Banner Description.
        /// </summary>
        [DatabaseField]
        public string BannerDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerDescription"), @"");
            }
            set
            {
                SetValue("BannerDescription", value);
            }
        }


        /// <summary>
        /// Banner Link.
        /// </summary>
        [DatabaseField]
        public Guid BannerLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("BannerLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("BannerLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// Banner Link Text.
        /// </summary>
        [DatabaseField]
        public string BannerLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerLinkText"), @"");
            }
            set
            {
                SetValue("BannerLinkText", value);
            }
        }


        /// <summary>
        /// Banner Image 1 (Desktop).
        /// </summary>
        [DatabaseField]
        public string BannerImage1
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerImage1"), @"");
            }
            set
            {
                SetValue("BannerImage1", value);
            }
        }


        /// <summary>
        /// Banner Image 2 (Tablet).
        /// </summary>
        [DatabaseField]
        public string BannerImage2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerImage2"), @"");
            }
            set
            {
                SetValue("BannerImage2", value);
            }
        }


        /// <summary>
        /// Banner Image 3 (Mobile).
        /// </summary>
        [DatabaseField]
        public string BannerImage3
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerImage3"), @"");
            }
            set
            {
                SetValue("BannerImage3", value);
            }
        }


        /// <summary>
        /// Banner Image Alt Text.
        /// </summary>
        [DatabaseField]
        public string BannerImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BannerImageAltText"), @"");
            }
            set
            {
                SetValue("BannerImageAltText", value);
            }
        }


        /// <summary>
        /// (Logged Out)Banner Header.
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerHeader"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerHeader", value);
            }
        }


        /// <summary>
        /// (Logged Out) Banner Title.
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerTitle"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerTitle", value);
            }
        }


        /// <summary>
        /// (Logged Out) Banner Description.
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerDescription"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerDescription", value);
            }
        }


        /// <summary>
        /// (Logged Out) Banner Link.
        /// </summary>
        [DatabaseField]
        public Guid LoggedOutBannerLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("LoggedOutBannerLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("LoggedOutBannerLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// (Logged Out) Banner Link Text.
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerLinkText"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerLinkText", value);
            }
        }


        /// <summary>
        /// Logged Out Banner Image 1 (Desktop).
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerImage1
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerImage1"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerImage1", value);
            }
        }


        /// <summary>
        /// Logged Out Banner Image 2 (Tablet).
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerImage2
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerImage2"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerImage2", value);
            }
        }


        /// <summary>
        /// Logged Out Banner Image 3 (Mobile).
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerImage3
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerImage3"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerImage3", value);
            }
        }


        /// <summary>
        /// Logged Out Banner Image Alt Text.
        /// </summary>
        [DatabaseField]
        public string LoggedOutBannerImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LoggedOutBannerImageAltText"), @"");
            }
            set
            {
                SetValue("LoggedOutBannerImageAltText", value);
            }
        }


        /// <summary>
        /// Spotlight Header.
        /// </summary>
        [DatabaseField]
        public string SpotlightHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SpotlightHeader"), @"");
            }
            set
            {
                SetValue("SpotlightHeader", value);
            }
        }


        /// <summary>
        /// Spotlight Description.
        /// </summary>
        [DatabaseField]
        public string SpotlightDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SpotlightDescription"), @"");
            }
            set
            {
                SetValue("SpotlightDescription", value);
            }
        }


        /// <summary>
        /// Spotlight Image.
        /// </summary>
        [DatabaseField]
        public string SpotlightImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SpotlightImage"), @"");
            }
            set
            {
                SetValue("SpotlightImage", value);
            }
        }


        /// <summary>
        /// Spotlight Image Alt Text.
        /// </summary>
        [DatabaseField]
        public string SpotlightImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SpotlightImageAltText"), @"");
            }
            set
            {
                SetValue("SpotlightImageAltText", value);
            }
        }


        /// <summary>
        /// Linked Page.
        /// </summary>
        [DatabaseField]
        public Guid SpotlightLinkedPageGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("SpotlightLinkedPageGuid"), Guid.Empty);
            }
            set
            {
                SetValue("SpotlightLinkedPageGuid", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string SpotlightLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SpotlightLinkText"), @"");
            }
            set
            {
                SetValue("SpotlightLinkText", value);
            }
        }


        /// <summary>
        /// Header.
        /// </summary>
        [DatabaseField]
        public string AlumniMovesHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniMovesHeader"), @"");
            }
            set
            {
                SetValue("AlumniMovesHeader", value);
            }
        }


        /// <summary>
        /// Linked Page.
        /// </summary>
        [DatabaseField]
        public Guid AlumniMovesLinkedPageGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("AlumniMovesLinkedPageGuid"), Guid.Empty);
            }
            set
            {
                SetValue("AlumniMovesLinkedPageGuid", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string AlumniMovesLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniMovesLinkText"), @"");
            }
            set
            {
                SetValue("AlumniMovesLinkText", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string AlumniMovesDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniMovesDescription"), @"");
            }
            set
            {
                SetValue("AlumniMovesDescription", value);
            }
        }


        /// <summary>
        /// Header.
        /// </summary>
        [DatabaseField]
        public string NewsHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsHeader"), @"");
            }
            set
            {
                SetValue("NewsHeader", value);
            }
        }


        /// <summary>
        /// Link.
        /// </summary>
        [DatabaseField]
        public Guid NewsLinkedPageGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("NewsLinkedPageGuid"), Guid.Empty);
            }
            set
            {
                SetValue("NewsLinkedPageGuid", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string NewsLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsLinkText"), @"");
            }
            set
            {
                SetValue("NewsLinkText", value);
            }
        }


        /// <summary>
        /// This displays when there are no available community news.
        /// </summary>
        [DatabaseField]
        public string NewsNoRecordsDisplay
        {
            get
            {
                return ValidationHelper.GetString(GetValue("NewsNoRecordsDisplay"), @"");
            }
            set
            {
                SetValue("NewsNoRecordsDisplay", value);
            }
        }


        /// <summary>
        /// Number Of Items To Display.
        /// </summary>
        [DatabaseField]
        public int NewsNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("NewsNumberOfItemsToDisplay"), 5);
            }
            set
            {
                SetValue("NewsNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Header.
        /// </summary>
        [DatabaseField]
        public string JobsHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobsHeader"), @"");
            }
            set
            {
                SetValue("JobsHeader", value);
            }
        }


        /// <summary>
        /// Link.
        /// </summary>
        [DatabaseField]
        public Guid JobLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("JobLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("JobLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string JobsLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobsLinkText"), @"");
            }
            set
            {
                SetValue("JobsLinkText", value);
            }
        }


        /// <summary>
        /// No Records Display.
        /// </summary>
        [DatabaseField]
        public string JobsNoRecordsDisplay
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobsNoRecordsDisplay"), @"");
            }
            set
            {
                SetValue("JobsNoRecordsDisplay", value);
            }
        }


        /// <summary>
        /// Number Of Items To Display.
        /// </summary>
        [DatabaseField]
        public int JobsNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("JobsNumberOfItemsToDisplay"), 5);
            }
            set
            {
                SetValue("JobsNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Boards Header.
        /// </summary>
        [DatabaseField]
        public string BoardsHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BoardsHeader"), @"");
            }
            set
            {
                SetValue("BoardsHeader", value);
            }
        }


        /// <summary>
        /// Link.
        /// </summary>
        [DatabaseField]
        public Guid BoardsLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("BoardsLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("BoardsLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// Link Text.
        /// </summary>
        [DatabaseField]
        public string BoardsLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BoardsLinkText"), @"");
            }
            set
            {
                SetValue("BoardsLinkText", value);
            }
        }


        /// <summary>
        /// No Records Display.
        /// </summary>
        [DatabaseField]
        public string BoardsNoRecordsDisplay
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BoardsNoRecordsDisplay"), @"");
            }
            set
            {
                SetValue("BoardsNoRecordsDisplay", value);
            }
        }


        /// <summary>
        /// Number of items to Display.
        /// </summary>
        [DatabaseField]
        public int BoardsNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BoardsNumberOfItemsToDisplay"), 0);
            }
            set
            {
                SetValue("BoardsNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Events Header.
        /// </summary>
        [DatabaseField]
        public string EventsHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EventsHeader"), @"");
            }
            set
            {
                SetValue("EventsHeader", value);
            }
        }


        /// <summary>
        /// Events Link.
        /// </summary>
        [DatabaseField]
        public Guid EventsLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("EventsLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("EventsLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// Events Link Text.
        /// </summary>
        [DatabaseField]
        public string EventsLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EventsLinkText"), @"");
            }
            set
            {
                SetValue("EventsLinkText", value);
            }
        }


        /// <summary>
        /// Events No Records Display.
        /// </summary>
        [DatabaseField]
        public string EventsNoRecordsDisplay
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EventsNoRecordsDisplay"), @"");
            }
            set
            {
                SetValue("EventsNoRecordsDisplay", value);
            }
        }


        /// <summary>
        /// EventsNumberOfItemsToDisplay.
        /// </summary>
        [DatabaseField]
        public int EventsNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("EventsNumberOfItemsToDisplay"), 0);
            }
            set
            {
                SetValue("EventsNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Resources Header.
        /// </summary>
        [DatabaseField]
        public string ResourcesHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ResourcesHeader"), @"");
            }
            set
            {
                SetValue("ResourcesHeader", value);
            }
        }


        /// <summary>
        /// Resources Link.
        /// </summary>
        [DatabaseField]
        public Guid ResourcesLinkedPageGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("ResourcesLinkedPageGUID"), Guid.Empty);
            }
            set
            {
                SetValue("ResourcesLinkedPageGUID", value);
            }
        }


        /// <summary>
        /// Resources Link Text.
        /// </summary>
        [DatabaseField]
        public string ResourcesLinkText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ResourcesLinkText"), @"");
            }
            set
            {
                SetValue("ResourcesLinkText", value);
            }
        }


        /// <summary>
        /// Resources No Records Display.
        /// </summary>
        [DatabaseField]
        public string ResourcesNoRecordsDisplay
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ResourcesNoRecordsDisplay"), @"");
            }
            set
            {
                SetValue("ResourcesNoRecordsDisplay", value);
            }
        }


        /// <summary>
        /// Number Of Items To Display.
        /// </summary>
        [DatabaseField]
        public int ResourcesNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ResourcesNumberOfItemsToDisplay"), 6);
            }
            set
            {
                SetValue("ResourcesNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Header.
        /// </summary>
        [DatabaseField]
        public string AlumniInTheMediaHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniInTheMediaHeader"), @"");
            }
            set
            {
                SetValue("AlumniInTheMediaHeader", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string AlumniInTheMediaDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniInTheMediaDescription"), @"");
            }
            set
            {
                SetValue("AlumniInTheMediaDescription", value);
            }
        }


        /// <summary>
        /// Number Of Items To Display.
        /// </summary>
        [DatabaseField]
        public int TwitterNumberOfItemsToDisplay
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TwitterNumberOfItemsToDisplay"), 0);
            }
            set
            {
                SetValue("TwitterNumberOfItemsToDisplay", value);
            }
        }


        /// <summary>
        /// Twitter Handle.
        /// </summary>
        [DatabaseField]
        public string TwitterHandle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TwitterHandle"), @"");
            }
            set
            {
                SetValue("TwitterHandle", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// When enabled, prevent site visitors from navigating to the page directly.
        /// If the page has any URLs associated with it, they will be removed.
        /// </summary>
        [DatabaseField]
        public bool DocumentMenuItemHideInNavigation1
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DocumentMenuItemHideInNavigation"), false);
            }
            set
            {
                SetValue("DocumentMenuItemHideInNavigation", value);
            }
        }


        /// <summary>
        /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultController
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultController"), @"");
            }
            set
            {
                SetValue("DefaultController", value);
            }
        }


        /// <summary>
        /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultAction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultAction"), @"");
            }
            set
            {
                SetValue("DefaultAction", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_Home fields.
        /// </summary>
        [RegisterProperty]
        public PageType_HomeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_Home fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_HomeFields : AbstractHierarchicalObject<PageType_HomeFields>
        {
            /// <summary>
            /// The content item of type PageType_Home that is a target of the extended API.
            /// </summary>
            private readonly PageType_Home mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_HomeFields" /> class with the specified content item of type PageType_Home.
            /// </summary>
            /// <param name="instance">The content item of type PageType_Home that is a target of the extended API.</param>
            public PageType_HomeFields(PageType_Home instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_HomePageID.
            /// </summary>
            public int PageID
            {
                get
                {
                    return mInstance.PageType_HomePageID;
                }
                set
                {
                    mInstance.PageType_HomePageID = value;
                }
            }


            /// <summary>
            /// Name of the item in the content tree.
            /// </summary>
            public string PageName
            {
                get
                {
                    return mInstance.PageName;
                }
                set
                {
                    mInstance.PageName = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Short Description.
            /// </summary>
            public string ShortDescription
            {
                get
                {
                    return mInstance.ShortDescription;
                }
                set
                {
                    mInstance.ShortDescription = value;
                }
            }


            /// <summary>
            /// Banner Header.
            /// </summary>
            public string BannerHeader
            {
                get
                {
                    return mInstance.BannerHeader;
                }
                set
                {
                    mInstance.BannerHeader = value;
                }
            }


            /// <summary>
            /// Banner Title.
            /// </summary>
            public string BannerTitle
            {
                get
                {
                    return mInstance.BannerTitle;
                }
                set
                {
                    mInstance.BannerTitle = value;
                }
            }


            /// <summary>
            /// Banner Description.
            /// </summary>
            public string BannerDescription
            {
                get
                {
                    return mInstance.BannerDescription;
                }
                set
                {
                    mInstance.BannerDescription = value;
                }
            }


            /// <summary>
            /// Banner Link.
            /// </summary>
            public Guid BannerLinkedPageGUID
            {
                get
                {
                    return mInstance.BannerLinkedPageGUID;
                }
                set
                {
                    mInstance.BannerLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// Banner Link Text.
            /// </summary>
            public string BannerLinkText
            {
                get
                {
                    return mInstance.BannerLinkText;
                }
                set
                {
                    mInstance.BannerLinkText = value;
                }
            }


            /// <summary>
            /// Banner Image 1 (Desktop).
            /// </summary>
            public string BannerImage1
            {
                get
                {
                    return mInstance.BannerImage1;
                }
                set
                {
                    mInstance.BannerImage1 = value;
                }
            }


            /// <summary>
            /// Banner Image 2 (Tablet).
            /// </summary>
            public string BannerImage2
            {
                get
                {
                    return mInstance.BannerImage2;
                }
                set
                {
                    mInstance.BannerImage2 = value;
                }
            }


            /// <summary>
            /// Banner Image 3 (Mobile).
            /// </summary>
            public string BannerImage3
            {
                get
                {
                    return mInstance.BannerImage3;
                }
                set
                {
                    mInstance.BannerImage3 = value;
                }
            }


            /// <summary>
            /// Banner Image Alt Text.
            /// </summary>
            public string BannerImageAltText
            {
                get
                {
                    return mInstance.BannerImageAltText;
                }
                set
                {
                    mInstance.BannerImageAltText = value;
                }
            }


            /// <summary>
            /// (Logged Out)Banner Header.
            /// </summary>
            public string LoggedOutBannerHeader
            {
                get
                {
                    return mInstance.LoggedOutBannerHeader;
                }
                set
                {
                    mInstance.LoggedOutBannerHeader = value;
                }
            }


            /// <summary>
            /// (Logged Out) Banner Title.
            /// </summary>
            public string LoggedOutBannerTitle
            {
                get
                {
                    return mInstance.LoggedOutBannerTitle;
                }
                set
                {
                    mInstance.LoggedOutBannerTitle = value;
                }
            }


            /// <summary>
            /// (Logged Out) Banner Description.
            /// </summary>
            public string LoggedOutBannerDescription
            {
                get
                {
                    return mInstance.LoggedOutBannerDescription;
                }
                set
                {
                    mInstance.LoggedOutBannerDescription = value;
                }
            }


            /// <summary>
            /// (Logged Out) Banner Link.
            /// </summary>
            public Guid LoggedOutBannerLinkedPageGUID
            {
                get
                {
                    return mInstance.LoggedOutBannerLinkedPageGUID;
                }
                set
                {
                    mInstance.LoggedOutBannerLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// (Logged Out) Banner Link Text.
            /// </summary>
            public string LoggedOutBannerLinkText
            {
                get
                {
                    return mInstance.LoggedOutBannerLinkText;
                }
                set
                {
                    mInstance.LoggedOutBannerLinkText = value;
                }
            }


            /// <summary>
            /// Logged Out Banner Image 1 (Desktop).
            /// </summary>
            public string LoggedOutBannerImage1
            {
                get
                {
                    return mInstance.LoggedOutBannerImage1;
                }
                set
                {
                    mInstance.LoggedOutBannerImage1 = value;
                }
            }


            /// <summary>
            /// Logged Out Banner Image 2 (Tablet).
            /// </summary>
            public string LoggedOutBannerImage2
            {
                get
                {
                    return mInstance.LoggedOutBannerImage2;
                }
                set
                {
                    mInstance.LoggedOutBannerImage2 = value;
                }
            }


            /// <summary>
            /// Logged Out Banner Image 3 (Mobile).
            /// </summary>
            public string LoggedOutBannerImage3
            {
                get
                {
                    return mInstance.LoggedOutBannerImage3;
                }
                set
                {
                    mInstance.LoggedOutBannerImage3 = value;
                }
            }


            /// <summary>
            /// Logged Out Banner Image Alt Text.
            /// </summary>
            public string LoggedOutBannerImageAltText
            {
                get
                {
                    return mInstance.LoggedOutBannerImageAltText;
                }
                set
                {
                    mInstance.LoggedOutBannerImageAltText = value;
                }
            }


            /// <summary>
            /// Spotlight Header.
            /// </summary>
            public string SpotlightHeader
            {
                get
                {
                    return mInstance.SpotlightHeader;
                }
                set
                {
                    mInstance.SpotlightHeader = value;
                }
            }


            /// <summary>
            /// Spotlight Description.
            /// </summary>
            public string SpotlightDescription
            {
                get
                {
                    return mInstance.SpotlightDescription;
                }
                set
                {
                    mInstance.SpotlightDescription = value;
                }
            }


            /// <summary>
            /// Spotlight Image.
            /// </summary>
            public string SpotlightImage
            {
                get
                {
                    return mInstance.SpotlightImage;
                }
                set
                {
                    mInstance.SpotlightImage = value;
                }
            }


            /// <summary>
            /// Spotlight Image Alt Text.
            /// </summary>
            public string SpotlightImageAltText
            {
                get
                {
                    return mInstance.SpotlightImageAltText;
                }
                set
                {
                    mInstance.SpotlightImageAltText = value;
                }
            }


            /// <summary>
            /// Linked Page.
            /// </summary>
            public Guid SpotlightLinkedPageGuid
            {
                get
                {
                    return mInstance.SpotlightLinkedPageGuid;
                }
                set
                {
                    mInstance.SpotlightLinkedPageGuid = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string SpotlightLinkText
            {
                get
                {
                    return mInstance.SpotlightLinkText;
                }
                set
                {
                    mInstance.SpotlightLinkText = value;
                }
            }


            /// <summary>
            /// Header.
            /// </summary>
            public string AlumniMovesHeader
            {
                get
                {
                    return mInstance.AlumniMovesHeader;
                }
                set
                {
                    mInstance.AlumniMovesHeader = value;
                }
            }


            /// <summary>
            /// Linked Page.
            /// </summary>
            public Guid AlumniMovesLinkedPageGuid
            {
                get
                {
                    return mInstance.AlumniMovesLinkedPageGuid;
                }
                set
                {
                    mInstance.AlumniMovesLinkedPageGuid = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string AlumniMovesLinkText
            {
                get
                {
                    return mInstance.AlumniMovesLinkText;
                }
                set
                {
                    mInstance.AlumniMovesLinkText = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string AlumniMovesDescription
            {
                get
                {
                    return mInstance.AlumniMovesDescription;
                }
                set
                {
                    mInstance.AlumniMovesDescription = value;
                }
            }


            /// <summary>
            /// Header.
            /// </summary>
            public string NewsHeader
            {
                get
                {
                    return mInstance.NewsHeader;
                }
                set
                {
                    mInstance.NewsHeader = value;
                }
            }


            /// <summary>
            /// Link.
            /// </summary>
            public Guid NewsLinkedPageGuid
            {
                get
                {
                    return mInstance.NewsLinkedPageGuid;
                }
                set
                {
                    mInstance.NewsLinkedPageGuid = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string NewsLinkText
            {
                get
                {
                    return mInstance.NewsLinkText;
                }
                set
                {
                    mInstance.NewsLinkText = value;
                }
            }


            /// <summary>
            /// This displays when there are no available community news.
            /// </summary>
            public string NewsNoRecordsDisplay
            {
                get
                {
                    return mInstance.NewsNoRecordsDisplay;
                }
                set
                {
                    mInstance.NewsNoRecordsDisplay = value;
                }
            }


            /// <summary>
            /// Number Of Items To Display.
            /// </summary>
            public int NewsNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.NewsNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.NewsNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Header.
            /// </summary>
            public string JobsHeader
            {
                get
                {
                    return mInstance.JobsHeader;
                }
                set
                {
                    mInstance.JobsHeader = value;
                }
            }


            /// <summary>
            /// Link.
            /// </summary>
            public Guid JobLinkedPageGUID
            {
                get
                {
                    return mInstance.JobLinkedPageGUID;
                }
                set
                {
                    mInstance.JobLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string JobsLinkText
            {
                get
                {
                    return mInstance.JobsLinkText;
                }
                set
                {
                    mInstance.JobsLinkText = value;
                }
            }


            /// <summary>
            /// No Records Display.
            /// </summary>
            public string JobsNoRecordsDisplay
            {
                get
                {
                    return mInstance.JobsNoRecordsDisplay;
                }
                set
                {
                    mInstance.JobsNoRecordsDisplay = value;
                }
            }


            /// <summary>
            /// Number Of Items To Display.
            /// </summary>
            public int JobsNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.JobsNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.JobsNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Boards Header.
            /// </summary>
            public string BoardsHeader
            {
                get
                {
                    return mInstance.BoardsHeader;
                }
                set
                {
                    mInstance.BoardsHeader = value;
                }
            }


            /// <summary>
            /// Link.
            /// </summary>
            public Guid BoardsLinkedPageGUID
            {
                get
                {
                    return mInstance.BoardsLinkedPageGUID;
                }
                set
                {
                    mInstance.BoardsLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// Link Text.
            /// </summary>
            public string BoardsLinkText
            {
                get
                {
                    return mInstance.BoardsLinkText;
                }
                set
                {
                    mInstance.BoardsLinkText = value;
                }
            }


            /// <summary>
            /// No Records Display.
            /// </summary>
            public string BoardsNoRecordsDisplay
            {
                get
                {
                    return mInstance.BoardsNoRecordsDisplay;
                }
                set
                {
                    mInstance.BoardsNoRecordsDisplay = value;
                }
            }


            /// <summary>
            /// Number of items to Display.
            /// </summary>
            public int BoardsNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.BoardsNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.BoardsNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Events Header.
            /// </summary>
            public string EventsHeader
            {
                get
                {
                    return mInstance.EventsHeader;
                }
                set
                {
                    mInstance.EventsHeader = value;
                }
            }


            /// <summary>
            /// Events Link.
            /// </summary>
            public Guid EventsLinkedPageGUID
            {
                get
                {
                    return mInstance.EventsLinkedPageGUID;
                }
                set
                {
                    mInstance.EventsLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// Events Link Text.
            /// </summary>
            public string EventsLinkText
            {
                get
                {
                    return mInstance.EventsLinkText;
                }
                set
                {
                    mInstance.EventsLinkText = value;
                }
            }


            /// <summary>
            /// Events No Records Display.
            /// </summary>
            public string EventsNoRecordsDisplay
            {
                get
                {
                    return mInstance.EventsNoRecordsDisplay;
                }
                set
                {
                    mInstance.EventsNoRecordsDisplay = value;
                }
            }


            /// <summary>
            /// EventsNumberOfItemsToDisplay.
            /// </summary>
            public int EventsNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.EventsNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.EventsNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Resources Header.
            /// </summary>
            public string ResourcesHeader
            {
                get
                {
                    return mInstance.ResourcesHeader;
                }
                set
                {
                    mInstance.ResourcesHeader = value;
                }
            }


            /// <summary>
            /// Resources Link.
            /// </summary>
            public Guid ResourcesLinkedPageGUID
            {
                get
                {
                    return mInstance.ResourcesLinkedPageGUID;
                }
                set
                {
                    mInstance.ResourcesLinkedPageGUID = value;
                }
            }


            /// <summary>
            /// Resources Link Text.
            /// </summary>
            public string ResourcesLinkText
            {
                get
                {
                    return mInstance.ResourcesLinkText;
                }
                set
                {
                    mInstance.ResourcesLinkText = value;
                }
            }


            /// <summary>
            /// Resources No Records Display.
            /// </summary>
            public string ResourcesNoRecordsDisplay
            {
                get
                {
                    return mInstance.ResourcesNoRecordsDisplay;
                }
                set
                {
                    mInstance.ResourcesNoRecordsDisplay = value;
                }
            }


            /// <summary>
            /// Number Of Items To Display.
            /// </summary>
            public int ResourcesNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.ResourcesNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.ResourcesNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Header.
            /// </summary>
            public string AlumniInTheMediaHeader
            {
                get
                {
                    return mInstance.AlumniInTheMediaHeader;
                }
                set
                {
                    mInstance.AlumniInTheMediaHeader = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string AlumniInTheMediaDescription
            {
                get
                {
                    return mInstance.AlumniInTheMediaDescription;
                }
                set
                {
                    mInstance.AlumniInTheMediaDescription = value;
                }
            }


            /// <summary>
            /// Number Of Items To Display.
            /// </summary>
            public int TwitterNumberOfItemsToDisplay
            {
                get
                {
                    return mInstance.TwitterNumberOfItemsToDisplay;
                }
                set
                {
                    mInstance.TwitterNumberOfItemsToDisplay = value;
                }
            }


            /// <summary>
            /// Twitter Handle.
            /// </summary>
            public string TwitterHandle
            {
                get
                {
                    return mInstance.TwitterHandle;
                }
                set
                {
                    mInstance.TwitterHandle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// CTAs that are to appear in the top widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> TopWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("TopWidgetZone");
                }
            }


            /// <summary>
            /// Related Content Widget Zone.
            /// </summary>
            public IEnumerable<TreeNode> RelatedContentWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("RelatedContentWidgetZone");
                }
            }


            /// <summary>
            /// When enabled, prevent site visitors from navigating to the page directly.
            /// If the page has any URLs associated with it, they will be removed.
            /// </summary>
            public bool DocumentMenuItemHideInNavigation
            {
                get
                {
                    return mInstance.DocumentMenuItemHideInNavigation1;
                }
                set
                {
                    mInstance.DocumentMenuItemHideInNavigation1 = value;
                }
            }


            /// <summary>
            /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultController
            {
                get
                {
                    return mInstance.DefaultController;
                }
                set
                {
                    mInstance.DefaultController = value;
                }
            }


            /// <summary>
            /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultAction
            {
                get
                {
                    return mInstance.DefaultAction;
                }
                set
                {
                    mInstance.DefaultAction = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_Home" /> class.
        /// </summary>
        public PageType_Home() : base(CLASS_NAME)
        {
            mFields = new PageType_HomeFields(this);
        }

        #endregion
    }
}
