//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using ECA.PageURL.Kentico.Models;

[assembly: RegisterCustomTable(CustomTable_PageURLItem.CLASS_NAME, typeof(CustomTable_PageURLItem))]

namespace ECA.PageURL.Kentico.Models
{
    /// <summary>
	/// Represents a content item of type CustomTable_PageURLItem.
	/// </summary>
	public partial class CustomTable_PageURLItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ECA.CustomTable_PageURL";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_PageURLItem fields.
        /// </summary>
        private readonly CustomTable_PageURLItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Page.
        /// </summary>
        [DatabaseField]
        public Guid NodeGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("NodeGUID"), Guid.Empty);
            }
            set
            {
                SetValue("NodeGUID", value);
            }
        }


        /// <summary>
        /// Culture.
        /// </summary>
        [DatabaseField]
        public string Culture
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Culture"), @"");
            }
            set
            {
                SetValue("Culture", value);
            }
        }


        /// <summary>
        /// URL Path.
        /// </summary>
        [DatabaseField]
        public string URLPath
        {
            get
            {
                return ValidationHelper.GetString(GetValue("URLPath"), @"");
            }
            set
            {
                SetValue("URLPath", value);
            }
        }


        /// <summary>
        /// Is Main URL.
        /// </summary>
        [DatabaseField]
        public bool IsMainURL
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsMainURL"), false);
            }
            set
            {
                SetValue("IsMainURL", value);
            }
        }


        /// <summary>
        /// Is Custom URL.
        /// </summary>
        [DatabaseField]
        public bool IsCustomURL
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsCustomURL"), true);
            }
            set
            {
                SetValue("IsCustomURL", value);
            }
        }


        /// <summary>
        /// Redirect Type.
        /// </summary>
        [DatabaseField]
        public string RedirectType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RedirectType"), @"");
            }
            set
            {
                SetValue("RedirectType", value);
            }
        }


        /// <summary>
        /// Is Canonical URL.
        /// </summary>
        [DatabaseField]
        public bool IsCanonicalURL
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsCanonicalURL"), false);
            }
            set
            {
                SetValue("IsCanonicalURL", value);
            }
        }


        /// <summary>
        /// Site.
        /// </summary>
        [DatabaseField]
        public int SiteID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SiteID"), 0);
            }
            set
            {
                SetValue("SiteID", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_PageURLItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_PageURLItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_PageURLItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CustomTable_PageURLItemFields : AbstractHierarchicalObject<CustomTable_PageURLItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_PageURLItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_PageURLItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_PageURLItemFields" /> class with the specified content item of type CustomTable_PageURLItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_PageURLItem that is a target of the extended API.</param>
            public CustomTable_PageURLItemFields(CustomTable_PageURLItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Page.
            /// </summary>
            public Guid NodeGUID
            {
                get
                {
                    return mInstance.NodeGUID;
                }
                set
                {
                    mInstance.NodeGUID = value;
                }
            }


            /// <summary>
            /// Culture.
            /// </summary>
            public string Culture
            {
                get
                {
                    return mInstance.Culture;
                }
                set
                {
                    mInstance.Culture = value;
                }
            }


            /// <summary>
            /// URL Path.
            /// </summary>
            public string URLPath
            {
                get
                {
                    return mInstance.URLPath;
                }
                set
                {
                    mInstance.URLPath = value;
                }
            }


            /// <summary>
            /// Is Main URL.
            /// </summary>
            public bool IsMainURL
            {
                get
                {
                    return mInstance.IsMainURL;
                }
                set
                {
                    mInstance.IsMainURL = value;
                }
            }


            /// <summary>
            /// Is Custom URL.
            /// </summary>
            public bool IsCustomURL
            {
                get
                {
                    return mInstance.IsCustomURL;
                }
                set
                {
                    mInstance.IsCustomURL = value;
                }
            }


            /// <summary>
            /// Redirect Type.
            /// </summary>
            public string RedirectType
            {
                get
                {
                    return mInstance.RedirectType;
                }
                set
                {
                    mInstance.RedirectType = value;
                }
            }


            /// <summary>
            /// Is Canonical URL.
            /// </summary>
            public bool IsCanonicalURL
            {
                get
                {
                    return mInstance.IsCanonicalURL;
                }
                set
                {
                    mInstance.IsCanonicalURL = value;
                }
            }


            /// <summary>
            /// Site.
            /// </summary>
            public int SiteID
            {
                get
                {
                    return mInstance.SiteID;
                }
                set
                {
                    mInstance.SiteID = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_PageURLItem" /> class.
        /// </summary>
        public CustomTable_PageURLItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_PageURLItemFields(this);
        }

        #endregion
    }
}