//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using ECA.PageURL.Kentico.Models;

[assembly: RegisterCustomTable(CustomTable_PathChangeItem.CLASS_NAME, typeof(CustomTable_PathChangeItem))]

namespace ECA.PageURL.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type CustomTable_PathChangeItem.
    /// </summary>
    public partial class CustomTable_PathChangeItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "ECA.CustomTable_PathChange";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_PathChangeItem fields.
        /// </summary>
        private readonly CustomTable_PathChangeItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Page.
        /// </summary>
        [DatabaseField]
        public Guid NodeGUID
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("NodeGUID"), Guid.Empty);
            }
            set
            {
                SetValue("NodeGUID", value);
            }
        }


        /// <summary>
        /// Culture.
        /// </summary>
        [DatabaseField]
        public string Culture
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Culture"), @"");
            }
            set
            {
                SetValue("Culture", value);
            }
        }


        /// <summary>
        /// Original Name Path.
        /// </summary>
        [DatabaseField]
        public string OriginalDocumentNamePath
        {
            get
            {
                return ValidationHelper.GetString(GetValue("OriginalDocumentNamePath"), @"");
            }
            set
            {
                SetValue("OriginalDocumentNamePath", value);
            }
        }


        /// <summary>
        /// Site.
        /// </summary>
        [DatabaseField]
        public int SiteID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SiteID"), 0);
            }
            set
            {
                SetValue("SiteID", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_PathChangeItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_PathChangeItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_PathChangeItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CustomTable_PathChangeItemFields : AbstractHierarchicalObject<CustomTable_PathChangeItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_PathChangeItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_PathChangeItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_PathChangeItemFields" /> class with the specified content item of type CustomTable_PathChangeItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_PathChangeItem that is a target of the extended API.</param>
            public CustomTable_PathChangeItemFields(CustomTable_PathChangeItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Page.
            /// </summary>
            public Guid NodeGUID
            {
                get
                {
                    return mInstance.NodeGUID;
                }
                set
                {
                    mInstance.NodeGUID = value;
                }
            }


            /// <summary>
            /// Culture.
            /// </summary>
            public string Culture
            {
                get
                {
                    return mInstance.Culture;
                }
                set
                {
                    mInstance.Culture = value;
                }
            }


            /// <summary>
            /// Original Name Path.
            /// </summary>
            public string OriginalDocumentNamePath
            {
                get
                {
                    return mInstance.OriginalDocumentNamePath;
                }
                set
                {
                    mInstance.OriginalDocumentNamePath = value;
                }
            }


            /// <summary>
            /// Site.
            /// </summary>
            public int SiteID
            {
                get
                {
                    return mInstance.SiteID;
                }
                set
                {
                    mInstance.SiteID = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_PathChangeItem" /> class.
        /// </summary>
        public CustomTable_PathChangeItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_PathChangeItemFields(this);
        }

        #endregion
    }
}