//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using OslerAlumni.OnePlace.Kentico.Models;

[assembly: RegisterDocumentType(PageType_OnePlaceQueries.CLASS_NAME, typeof(PageType_OnePlaceQueries))]

namespace OslerAlumni.OnePlace.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_OnePlaceQueries.
    /// </summary>
    public partial class PageType_OnePlaceQueries : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_OnePlaceQueries";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_OnePlaceQueries fields.
        /// </summary>
        private readonly PageType_OnePlaceQueriesFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Gets an object that provides extended API for working with PageType_OnePlaceQueries fields.
        /// </summary>
        [RegisterProperty]
        public PageType_OnePlaceQueriesFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_OnePlaceQueries fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_OnePlaceQueriesFields : AbstractHierarchicalObject<PageType_OnePlaceQueriesFields>
        {
            /// <summary>
            /// The content item of type PageType_OnePlaceQueries that is a target of the extended API.
            /// </summary>
            private readonly PageType_OnePlaceQueries mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_OnePlaceQueriesFields" /> class with the specified content item of type PageType_OnePlaceQueries.
            /// </summary>
            /// <param name="instance">The content item of type PageType_OnePlaceQueries that is a target of the extended API.</param>
            public PageType_OnePlaceQueriesFields(PageType_OnePlaceQueries instance)
            {
                mInstance = instance;
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_OnePlaceQueries" /> class.
        /// </summary>
        public PageType_OnePlaceQueries() : base(CLASS_NAME)
        {
            mFields = new PageType_OnePlaceQueriesFields(this);
        }

        #endregion
    }
}