//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using OslerAlumni.Core.Kentico.Models;

[assembly: RegisterCustomTable(CustomTable_BoardOpportunitySourceItem.CLASS_NAME, typeof(CustomTable_BoardOpportunitySourceItem))]

namespace OslerAlumni.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type CustomTable_BoardOpportunitySourceItem.
    /// </summary>
    public partial class CustomTable_BoardOpportunitySourceItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.CustomTable_BoardOpportunitySource";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_BoardOpportunitySourceItem fields.
        /// </summary>
        private readonly CustomTable_BoardOpportunitySourceItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Company Name.
        /// </summary>
        [DatabaseField]
        public string CompanyName
        {
            get { return ValidationHelper.GetString(GetValue("CompanyName"), @""); }
            set { SetValue("CompanyName", value); }
        }


        /// <summary>
        /// Source Code Name.
        /// </summary>
        [DatabaseField]
        public string CodeName
        {
            get { return ValidationHelper.GetString(GetValue("CodeName"), @""); }
            set { SetValue("CodeName", value); }
        }


        /// <summary>
        /// Logo (English).
        /// </summary>
        [DatabaseField]
        public string LogoEn
        {
            get { return ValidationHelper.GetString(GetValue("LogoEn"), @""); }
            set { SetValue("LogoEn", value); }
        }


        /// <summary>
        /// Logo (French).
        /// </summary>
        [DatabaseField]
        public string LogoFr
        {
            get { return ValidationHelper.GetString(GetValue("LogoFr"), @""); }
            set { SetValue("LogoFr", value); }
        }


        /// <summary>
        /// Logo alt text.
        /// </summary>
        [DatabaseField]
        public string LogoAltText
        {
            get { return ValidationHelper.GetString(GetValue("LogoAltText"), @""); }
            set { SetValue("LogoAltText", value); }
        }


        /// <summary>
        /// Enabled.
        /// </summary>
        [DatabaseField]
        public bool Enabled
        {
            get { return ValidationHelper.GetBoolean(GetValue("Enabled"), true); }
            set { SetValue("Enabled", value); }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_BoardOpportunitySourceItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_BoardOpportunitySourceItemFields Fields
        {
            get { return mFields; }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_BoardOpportunitySourceItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class
            CustomTable_BoardOpportunitySourceItemFields : AbstractHierarchicalObject<
                CustomTable_BoardOpportunitySourceItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_BoardOpportunitySourceItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_BoardOpportunitySourceItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_BoardOpportunitySourceItemFields" /> class with the specified content item of type CustomTable_BoardOpportunitySourceItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_BoardOpportunitySourceItem that is a target of the extended API.</param>
            public CustomTable_BoardOpportunitySourceItemFields(CustomTable_BoardOpportunitySourceItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Company Name.
            /// </summary>
            public string CompanyName
            {
                get { return mInstance.CompanyName; }
                set { mInstance.CompanyName = value; }
            }


            /// <summary>
            /// Source Code Name.
            /// </summary>
            public string CodeName
            {
                get { return mInstance.CodeName; }
                set { mInstance.CodeName = value; }
            }


            /// <summary>
            /// Logo (English).
            /// </summary>
            public string LogoEn
            {
                get { return mInstance.LogoEn; }
                set { mInstance.LogoEn = value; }
            }


            /// <summary>
            /// Logo (French).
            /// </summary>
            public string LogoFr
            {
                get { return mInstance.LogoFr; }
                set { mInstance.LogoFr = value; }
            }


            /// <summary>
            /// Logo alt text.
            /// </summary>
            public string LogoAltText
            {
                get { return mInstance.LogoAltText; }
                set { mInstance.LogoAltText = value; }
            }


            /// <summary>
            /// Enabled.
            /// </summary>
            public bool Enabled
            {
                get { return mInstance.Enabled; }
                set { mInstance.Enabled = value; }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_BoardOpportunitySourceItem" /> class.
        /// </summary>
        public CustomTable_BoardOpportunitySourceItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_BoardOpportunitySourceItemFields(this);
        }

        #endregion
    }
}
