//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;

using OslerAlumni.Core.Kentico.Models;

[assembly: RegisterDocumentType(PageType_Profile.CLASS_NAME, typeof(PageType_Profile))]

namespace OslerAlumni.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Profile.
    /// </summary>
    public partial class PageType_Profile : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_Profile";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_Profile fields.
        /// </summary>
        private readonly PageType_ProfileFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_ProfileID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_ProfileID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_ProfileID"), 0);
            }
            set
            {
                SetValue("PageType_ProfileID", value);
            }
        }


        /// <summary>
        /// Profile Image.
        /// </summary>
        [DatabaseField]
        public string ProfileImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ProfileImage"), @"");
            }
            set
            {
                SetValue("ProfileImage", value);
            }
        }


        /// <summary>
        /// Name of the item in the content tree.
        /// </summary>
        [DatabaseField]
        public string PageName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageName"), @"");
            }
            set
            {
                SetValue("PageName", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Short Description.
        /// </summary>
        [DatabaseField]
        public string ShortDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ShortDescription"), @"");
            }
            set
            {
                SetValue("ShortDescription", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// User GUID.
        /// </summary>
        [DatabaseField]
        public Guid UserGuid
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("UserGuid"), Guid.Empty);
            }
            set
            {
                SetValue("UserGuid", value);
            }
        }


        /// <summary>
        /// OnePlace Reference.
        /// </summary>
        [DatabaseField]
        public string OnePlaceReference
        {
            get
            {
                return ValidationHelper.GetString(GetValue("OnePlaceReference"), @"");
            }
            set
            {
                SetValue("OnePlaceReference", value);
            }
        }


        /// <summary>
        /// Start Date At Osler.
        /// </summary>
        [DatabaseField]
        public DateTime StartDateAtOsler
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("StartDateAtOsler"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("StartDateAtOsler", value);
            }
        }


        /// <summary>
        /// End Date At Osler.
        /// </summary>
        [DatabaseField]
        public DateTime EndDateAtOsler
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("EndDateAtOsler"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("EndDateAtOsler", value);
            }
        }


        /// <summary>
        /// First Name.
        /// </summary>
        [DatabaseField]
        public string FirstName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("FirstName"), @"");
            }
            set
            {
                SetValue("FirstName", value);
            }
        }


        /// <summary>
        /// Last Name.
        /// </summary>
        [DatabaseField]
        public string LastName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastName"), @"");
            }
            set
            {
                SetValue("LastName", value);
            }
        }


        /// <summary>
        /// LastNameNormalized.
        /// </summary>
        [DatabaseField]
        public string LastNameNormalized
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LastNameNormalized"), @"");
            }
            set
            {
                SetValue("LastNameNormalized", value);
            }
        }


        /// <summary>
        /// Email.
        /// </summary>
        [DatabaseField]
        public string AlumniEmail
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AlumniEmail"), @"");
            }
            set
            {
                SetValue("AlumniEmail", value);
            }
        }


        /// <summary>
        /// City.
        /// </summary>
        [DatabaseField]
        public string City
        {
            get
            {
                return ValidationHelper.GetString(GetValue("City"), @"");
            }
            set
            {
                SetValue("City", value);
            }
        }


        /// <summary>
        /// Province.
        /// </summary>
        [DatabaseField]
        public string Province
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Province"), @"");
            }
            set
            {
                SetValue("Province", value);
            }
        }


        /// <summary>
        /// Country.
        /// </summary>
        [DatabaseField]
        public string Country
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Country"), @"");
            }
            set
            {
                SetValue("Country", value);
            }
        }


        /// <summary>
        /// Job Title.
        /// </summary>
        [DatabaseField]
        public string JobTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobTitle"), @"");
            }
            set
            {
                SetValue("JobTitle", value);
            }
        }


        /// <summary>
        /// Company.
        /// </summary>
        [DatabaseField]
        public string ProfileCompany
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ProfileCompany"), @"");
            }
            set
            {
                SetValue("ProfileCompany", value);
            }
        }


        /// <summary>
        /// Years And Jurisdictions.
        /// </summary>
        [DatabaseField]
        public string YearsAndJurisdictions
        {
            get
            {
                return ValidationHelper.GetString(GetValue("YearsAndJurisdictions"), @"");
            }
            set
            {
                SetValue("YearsAndJurisdictions", value);
            }
        }


        /// <summary>
        /// Current Industry.
        /// </summary>
        [DatabaseField]
        public string CurrentIndustry
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CurrentIndustry"), @"");
            }
            set
            {
                SetValue("CurrentIndustry", value);
            }
        }


        /// <summary>
        /// Board Memberships.
        /// </summary>
        [DatabaseField]
        public string BoardMemberships
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BoardMemberships"), @"");
            }
            set
            {
                SetValue("BoardMemberships", value);
            }
        }


        /// <summary>
        /// Office Locations.
        /// </summary>
        [DatabaseField]
        public string OfficeLocations
        {
            get
            {
                return ValidationHelper.GetString(GetValue("OfficeLocations"), @"");
            }
            set
            {
                SetValue("OfficeLocations", value);
            }
        }


        /// <summary>
        /// Practice Areas.
        /// </summary>
        [DatabaseField]
        public string PracticeAreas
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PracticeAreas"), @"");
            }
            set
            {
                SetValue("PracticeAreas", value);
            }
        }


        /// <summary>
        /// Include Email In Directory.
        /// </summary>
        [DatabaseField]
        public bool IncludeEmailInDirectory
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IncludeEmailInDirectory"), false);
            }
            set
            {
                SetValue("IncludeEmailInDirectory", value);
            }
        }


        /// <summary>
        /// Display Image In Directory.
        /// </summary>
        [DatabaseField]
        public bool DisplayImageInDirectory
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DisplayImageInDirectory"), false);
            }
            set
            {
                SetValue("DisplayImageInDirectory", value);
            }
        }


        /// <summary>
        /// LinkedIn Profile Url (Optional).
        /// </summary>
        [DatabaseField]
        public string LinkedInUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkedInUrl"), @"");
            }
            set
            {
                SetValue("LinkedInUrl", value);
            }
        }


        /// <summary>
        /// Twitter Url (Optional).
        /// </summary>
        [DatabaseField]
        public string TwitterUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("TwitterUrl"), @"");
            }
            set
            {
                SetValue("TwitterUrl", value);
            }
        }


        /// <summary>
        /// Instagram Url (Optional).
        /// </summary>
        [DatabaseField]
        public string InstagramUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("InstagramUrl"), @"");
            }
            set
            {
                SetValue("InstagramUrl", value);
            }
        }


        /// <summary>
        /// Education Overview.
        /// </summary>
        [DatabaseField]
        public string EducationOverview
        {
            get
            {
                return ValidationHelper.GetString(GetValue("EducationOverview"), @"");
            }
            set
            {
                SetValue("EducationOverview", value);
            }
        }


        /// <summary>
        /// When enabled, prevent site visitors from navigating to the page directly.
        /// If the page has any URLs associated with it, they will be removed.
        /// </summary>
        [DatabaseField]
        public bool DocumentMenuItemHideInNavigation1
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DocumentMenuItemHideInNavigation"), false);
            }
            set
            {
                SetValue("DocumentMenuItemHideInNavigation", value);
            }
        }


        /// <summary>
        /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultController
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultController"), @"");
            }
            set
            {
                SetValue("DefaultController", value);
            }
        }


        /// <summary>
        /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultAction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultAction"), @"");
            }
            set
            {
                SetValue("DefaultAction", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_Profile fields.
        /// </summary>
        [RegisterProperty]
        public PageType_ProfileFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_Profile fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_ProfileFields : AbstractHierarchicalObject<PageType_ProfileFields>
        {
            /// <summary>
            /// The content item of type PageType_Profile that is a target of the extended API.
            /// </summary>
            private readonly PageType_Profile mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_ProfileFields" /> class with the specified content item of type PageType_Profile.
            /// </summary>
            /// <param name="instance">The content item of type PageType_Profile that is a target of the extended API.</param>
            public PageType_ProfileFields(PageType_Profile instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_ProfileID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_ProfileID;
                }
                set
                {
                    mInstance.PageType_ProfileID = value;
                }
            }


            /// <summary>
            /// Profile Image.
            /// </summary>
            public string ProfileImage
            {
                get
                {
                    return mInstance.ProfileImage;
                }
                set
                {
                    mInstance.ProfileImage = value;
                }
            }


            /// <summary>
            /// Name of the item in the content tree.
            /// </summary>
            public string PageName
            {
                get
                {
                    return mInstance.PageName;
                }
                set
                {
                    mInstance.PageName = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Short Description.
            /// </summary>
            public string ShortDescription
            {
                get
                {
                    return mInstance.ShortDescription;
                }
                set
                {
                    mInstance.ShortDescription = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// User GUID.
            /// </summary>
            public Guid UserGuid
            {
                get
                {
                    return mInstance.UserGuid;
                }
                set
                {
                    mInstance.UserGuid = value;
                }
            }


            /// <summary>
            /// OnePlace Reference.
            /// </summary>
            public string OnePlaceReference
            {
                get
                {
                    return mInstance.OnePlaceReference;
                }
                set
                {
                    mInstance.OnePlaceReference = value;
                }
            }


            /// <summary>
            /// Start Date At Osler.
            /// </summary>
            public DateTime StartDateAtOsler
            {
                get
                {
                    return mInstance.StartDateAtOsler;
                }
                set
                {
                    mInstance.StartDateAtOsler = value;
                }
            }


            /// <summary>
            /// End Date At Osler.
            /// </summary>
            public DateTime EndDateAtOsler
            {
                get
                {
                    return mInstance.EndDateAtOsler;
                }
                set
                {
                    mInstance.EndDateAtOsler = value;
                }
            }


            /// <summary>
            /// First Name.
            /// </summary>
            public string FirstName
            {
                get
                {
                    return mInstance.FirstName;
                }
                set
                {
                    mInstance.FirstName = value;
                }
            }


            /// <summary>
            /// Last Name.
            /// </summary>
            public string LastName
            {
                get
                {
                    return mInstance.LastName;
                }
                set
                {
                    mInstance.LastName = value;
                }
            }


            /// <summary>
            /// LastNameNormalized.
            /// </summary>
            public string LastNameNormalized
            {
                get
                {
                    return mInstance.LastNameNormalized;
                }
                set
                {
                    mInstance.LastNameNormalized = value;
                }
            }


            /// <summary>
            /// Email.
            /// </summary>
            public string AlumniEmail
            {
                get
                {
                    return mInstance.AlumniEmail;
                }
                set
                {
                    mInstance.AlumniEmail = value;
                }
            }


            /// <summary>
            /// City.
            /// </summary>
            public string City
            {
                get
                {
                    return mInstance.City;
                }
                set
                {
                    mInstance.City = value;
                }
            }


            /// <summary>
            /// Province.
            /// </summary>
            public string Province
            {
                get
                {
                    return mInstance.Province;
                }
                set
                {
                    mInstance.Province = value;
                }
            }


            /// <summary>
            /// Country.
            /// </summary>
            public string Country
            {
                get
                {
                    return mInstance.Country;
                }
                set
                {
                    mInstance.Country = value;
                }
            }


            /// <summary>
            /// Job Title.
            /// </summary>
            public string JobTitle
            {
                get
                {
                    return mInstance.JobTitle;
                }
                set
                {
                    mInstance.JobTitle = value;
                }
            }


            /// <summary>
            /// Company.
            /// </summary>
            public string ProfileCompany
            {
                get
                {
                    return mInstance.ProfileCompany;
                }
                set
                {
                    mInstance.ProfileCompany = value;
                }
            }


            /// <summary>
            /// Years And Jurisdictions.
            /// </summary>
            public string YearsAndJurisdictions
            {
                get
                {
                    return mInstance.YearsAndJurisdictions;
                }
                set
                {
                    mInstance.YearsAndJurisdictions = value;
                }
            }


            /// <summary>
            /// Current Industry.
            /// </summary>
            public string CurrentIndustry
            {
                get
                {
                    return mInstance.CurrentIndustry;
                }
                set
                {
                    mInstance.CurrentIndustry = value;
                }
            }


            /// <summary>
            /// Board Memberships.
            /// </summary>
            public string BoardMemberships
            {
                get
                {
                    return mInstance.BoardMemberships;
                }
                set
                {
                    mInstance.BoardMemberships = value;
                }
            }


            /// <summary>
            /// Office Locations.
            /// </summary>
            public string OfficeLocations
            {
                get
                {
                    return mInstance.OfficeLocations;
                }
                set
                {
                    mInstance.OfficeLocations = value;
                }
            }


            /// <summary>
            /// Practice Areas.
            /// </summary>
            public string PracticeAreas
            {
                get
                {
                    return mInstance.PracticeAreas;
                }
                set
                {
                    mInstance.PracticeAreas = value;
                }
            }


            /// <summary>
            /// Include Email In Directory.
            /// </summary>
            public bool IncludeEmailInDirectory
            {
                get
                {
                    return mInstance.IncludeEmailInDirectory;
                }
                set
                {
                    mInstance.IncludeEmailInDirectory = value;
                }
            }


            /// <summary>
            /// Display Image In Directory.
            /// </summary>
            public bool DisplayImageInDirectory
            {
                get
                {
                    return mInstance.DisplayImageInDirectory;
                }
                set
                {
                    mInstance.DisplayImageInDirectory = value;
                }
            }


            /// <summary>
            /// LinkedIn Profile Url (Optional).
            /// </summary>
            public string LinkedInUrl
            {
                get
                {
                    return mInstance.LinkedInUrl;
                }
                set
                {
                    mInstance.LinkedInUrl = value;
                }
            }


            /// <summary>
            /// Twitter Url (Optional).
            /// </summary>
            public string TwitterUrl
            {
                get
                {
                    return mInstance.TwitterUrl;
                }
                set
                {
                    mInstance.TwitterUrl = value;
                }
            }


            /// <summary>
            /// Instagram Url (Optional).
            /// </summary>
            public string InstagramUrl
            {
                get
                {
                    return mInstance.InstagramUrl;
                }
                set
                {
                    mInstance.InstagramUrl = value;
                }
            }


            /// <summary>
            /// Education Overview.
            /// </summary>
            public string EducationOverview
            {
                get
                {
                    return mInstance.EducationOverview;
                }
                set
                {
                    mInstance.EducationOverview = value;
                }
            }


            /// <summary>
            /// CTAs that are to appear in the top widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> TopWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("TopWidgetZone");
                }
            }


            /// <summary>
            /// Related Content Widget Zone.
            /// </summary>
            public IEnumerable<TreeNode> RelatedContentWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("RelatedContentWidgetZone");
                }
            }


            /// <summary>
            /// When enabled, prevent site visitors from navigating to the page directly.
            /// If the page has any URLs associated with it, they will be removed.
            /// </summary>
            public bool DocumentMenuItemHideInNavigation
            {
                get
                {
                    return mInstance.DocumentMenuItemHideInNavigation1;
                }
                set
                {
                    mInstance.DocumentMenuItemHideInNavigation1 = value;
                }
            }


            /// <summary>
            /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultController
            {
                get
                {
                    return mInstance.DefaultController;
                }
                set
                {
                    mInstance.DefaultController = value;
                }
            }


            /// <summary>
            /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultAction
            {
                get
                {
                    return mInstance.DefaultAction;
                }
                set
                {
                    mInstance.DefaultAction = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_Profile" /> class.
        /// </summary>
        public PageType_Profile() : base(CLASS_NAME)
        {
            mFields = new PageType_ProfileFields(this);
        }

        #endregion
    }
}
