//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using OslerAlumni.Mvc.Core.Kentico.Models;

[assembly: RegisterDocumentType(PageType_Page.CLASS_NAME, typeof(PageType_Page))]

namespace OslerAlumni.Mvc.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Page.
    /// </summary>
    public partial class PageType_Page : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_Page";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_Page fields.
        /// </summary>
        private readonly PageType_PageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_PageID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_PageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_PageID"), 0);
            }
            set
            {
                SetValue("PageType_PageID", value);
            }
        }


        /// <summary>
        /// Name of the item in the content tree.
        /// </summary>
        [DatabaseField]
        public string PageName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageName"), @"");
            }
            set
            {
                SetValue("PageName", value);
            }
        }


        /// <summary>
        /// IsPublic.
        /// </summary>
        [DatabaseField]
        public bool IsPublic
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("IsPublic"), false);
            }
            set
            {
                SetValue("IsPublic", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Short Description.
        /// </summary>
        [DatabaseField]
        public string ShortDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ShortDescription"), @"");
            }
            set
            {
                SetValue("ShortDescription", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Has Success State.
        /// </summary>
        [DatabaseField]
        public bool HasSuccessState
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("HasSuccessState"), false);
            }
            set
            {
                SetValue("HasSuccessState", value);
            }
        }


        /// <summary>
        /// Success Header.
        /// </summary>
        [DatabaseField]
        public string SuccessHeader
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SuccessHeader"), @"");
            }
            set
            {
                SetValue("SuccessHeader", value);
            }
        }


        /// <summary>
        /// Success Description.
        /// </summary>
        [DatabaseField]
        public string SuccessDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SuccessDescription"), @"");
            }
            set
            {
                SetValue("SuccessDescription", value);
            }
        }


        /// <summary>
        /// When enabled, prevent site visitors from navigating to the page directly.
        /// If the page has any URLs associated with it, they will be removed.
        /// </summary>
        [DatabaseField]
        public bool DocumentMenuItemHideInNavigation1
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DocumentMenuItemHideInNavigation"), false);
            }
            set
            {
                SetValue("DocumentMenuItemHideInNavigation", value);
            }
        }


        /// <summary>
        /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultController
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultController"), @"");
            }
            set
            {
                SetValue("DefaultController", value);
            }
        }


        /// <summary>
        /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultAction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultAction"), @"");
            }
            set
            {
                SetValue("DefaultAction", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_Page fields.
        /// </summary>
        [RegisterProperty]
        public PageType_PageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_Page fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_PageFields : AbstractHierarchicalObject<PageType_PageFields>
        {
            /// <summary>
            /// The content item of type PageType_Page that is a target of the extended API.
            /// </summary>
            private readonly PageType_Page mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_PageFields" /> class with the specified content item of type PageType_Page.
            /// </summary>
            /// <param name="instance">The content item of type PageType_Page that is a target of the extended API.</param>
            public PageType_PageFields(PageType_Page instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_PageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_PageID;
                }
                set
                {
                    mInstance.PageType_PageID = value;
                }
            }


            /// <summary>
            /// Name of the item in the content tree.
            /// </summary>
            public string PageName
            {
                get
                {
                    return mInstance.PageName;
                }
                set
                {
                    mInstance.PageName = value;
                }
            }


            /// <summary>
            /// IsPublic.
            /// </summary>
            public bool IsPublic
            {
                get
                {
                    return mInstance.IsPublic;
                }
                set
                {
                    mInstance.IsPublic = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Short Description.
            /// </summary>
            public string ShortDescription
            {
                get
                {
                    return mInstance.ShortDescription;
                }
                set
                {
                    mInstance.ShortDescription = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Has Success State.
            /// </summary>
            public bool HasSuccessState
            {
                get
                {
                    return mInstance.HasSuccessState;
                }
                set
                {
                    mInstance.HasSuccessState = value;
                }
            }


            /// <summary>
            /// Success Header.
            /// </summary>
            public string SuccessHeader
            {
                get
                {
                    return mInstance.SuccessHeader;
                }
                set
                {
                    mInstance.SuccessHeader = value;
                }
            }


            /// <summary>
            /// Success Description.
            /// </summary>
            public string SuccessDescription
            {
                get
                {
                    return mInstance.SuccessDescription;
                }
                set
                {
                    mInstance.SuccessDescription = value;
                }
            }


            /// <summary>
            /// CTAs that are to appear in the top widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> TopWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("TopWidgetZone");
                }
            }


            /// <summary>
            /// Related Content Widget Zone.
            /// </summary>
            public IEnumerable<TreeNode> RelatedContentWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("RelatedContentWidgetZone");
                }
            }


            /// <summary>
            /// When enabled, prevent site visitors from navigating to the page directly.
            /// If the page has any URLs associated with it, they will be removed.
            /// </summary>
            public bool DocumentMenuItemHideInNavigation
            {
                get
                {
                    return mInstance.DocumentMenuItemHideInNavigation1;
                }
                set
                {
                    mInstance.DocumentMenuItemHideInNavigation1 = value;
                }
            }


            /// <summary>
            /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultController
            {
                get
                {
                    return mInstance.DefaultController;
                }
                set
                {
                    mInstance.DefaultController = value;
                }
            }


            /// <summary>
            /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultAction
            {
                get
                {
                    return mInstance.DefaultAction;
                }
                set
                {
                    mInstance.DefaultAction = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_Page" /> class.
        /// </summary>
        public PageType_Page() : base(CLASS_NAME)
        {
            mFields = new PageType_PageFields(this);
        }

        #endregion
    }
}
