//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using OslerAlumni.Mvc.Core.Kentico.Models;

[assembly: RegisterDocumentType(PageType_Job.CLASS_NAME, typeof(PageType_Job))]

namespace OslerAlumni.Mvc.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Job.
    /// </summary>
    public partial class PageType_Job : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "OslerAlumni.PageType_Job";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_Job fields.
        /// </summary>
        private readonly PageType_JobFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_JobID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_JobID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_JobID"), 0);
            }
            set
            {
                SetValue("PageType_JobID", value);
            }
        }


        /// <summary>
        /// Name of the item in the content tree.
        /// </summary>
        [DatabaseField]
        public string PageName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("PageName"), @"");
            }
            set
            {
                SetValue("PageName", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Short Description.
        /// </summary>
        [DatabaseField]
        public string ShortDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ShortDescription"), @"");
            }
            set
            {
                SetValue("ShortDescription", value);
            }
        }


        /// <summary>
        /// Company.
        /// </summary>
        [DatabaseField]
        public string Company
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Company"), @"");
            }
            set
            {
                SetValue("Company", value);
            }
        }


        /// <summary>
        /// Job Location.
        /// </summary>
        [DatabaseField]
        public string JobLocation
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobLocation"), @"");
            }
            set
            {
                SetValue("JobLocation", value);
            }
        }


        /// <summary>
        /// Job Classification.
        /// </summary>
        [DatabaseField]
        public string JobClassification
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobClassification"), @"Osler");
            }
            set
            {
                SetValue("JobClassification", value);
            }
        }


        /// <summary>
        /// Job Category.
        /// </summary>
        [DatabaseField]
        public string JobCategoryCodeName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobCategoryCodeName"), @"");
            }
            set
            {
                SetValue("JobCategoryCodeName", value);
            }
        }


        /// <summary>
        /// Posted Date.
        /// </summary>
        [DatabaseField]
        public DateTime PostedDate
        {
            get
            {
                return ValidationHelper.GetDateTime(GetValue("PostedDate"), DateTimeHelper.ZERO_TIME);
            }
            set
            {
                SetValue("PostedDate", value);
            }
        }


        /// <summary>
        /// External Url.
        /// </summary>
        [DatabaseField]
        public string ExternalUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ExternalUrl"), @"");
            }
            set
            {
                SetValue("ExternalUrl", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// When enabled, prevent site visitors from navigating to the page directly.
        /// If the page has any URLs associated with it, they will be removed.
        /// </summary>
        [DatabaseField]
        public bool DocumentMenuItemHideInNavigation1
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("DocumentMenuItemHideInNavigation"), false);
            }
            set
            {
                SetValue("DocumentMenuItemHideInNavigation", value);
            }
        }


        /// <summary>
        /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultController
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultController"), @"");
            }
            set
            {
                SetValue("DefaultController", value);
            }
        }


        /// <summary>
        /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
        /// </summary>
        [DatabaseField]
        public string DefaultAction
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DefaultAction"), @"");
            }
            set
            {
                SetValue("DefaultAction", value);
            }
        }

        /// <summary>
        /// Gets an object that provides extended API for working with PageType_Job fields.
        /// </summary>
        [RegisterProperty]
        public PageType_JobFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_Job fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_JobFields : AbstractHierarchicalObject<PageType_JobFields>
        {
            /// <summary>
            /// The content item of type PageType_Job that is a target of the extended API.
            /// </summary>
            private readonly PageType_Job mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_JobFields" /> class with the specified content item of type PageType_Job.
            /// </summary>
            /// <param name="instance">The content item of type PageType_Job that is a target of the extended API.</param>
            public PageType_JobFields(PageType_Job instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_JobID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_JobID;
                }
                set
                {
                    mInstance.PageType_JobID = value;
                }
            }


            /// <summary>
            /// Name of the item in the content tree.
            /// </summary>
            public string PageName
            {
                get
                {
                    return mInstance.PageName;
                }
                set
                {
                    mInstance.PageName = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Short Description.
            /// </summary>
            public string ShortDescription
            {
                get
                {
                    return mInstance.ShortDescription;
                }
                set
                {
                    mInstance.ShortDescription = value;
                }
            }


            /// <summary>
            /// Company.
            /// </summary>
            public string Company
            {
                get
                {
                    return mInstance.Company;
                }
                set
                {
                    mInstance.Company = value;
                }
            }


            /// <summary>
            /// Job Location.
            /// </summary>
            public string JobLocation
            {
                get
                {
                    return mInstance.JobLocation;
                }
                set
                {
                    mInstance.JobLocation = value;
                }
            }


            /// <summary>
            /// Job Classification.
            /// </summary>
            public string JobClassification
            {
                get
                {
                    return mInstance.JobClassification;
                }
                set
                {
                    mInstance.JobClassification = value;
                }
            }


            /// <summary>
            /// Job Category.
            /// </summary>
            public string JobCategoryCodeName
            {
                get
                {
                    return mInstance.JobCategoryCodeName;
                }
                set
                {
                    mInstance.JobCategoryCodeName = value;
                }
            }


            /// <summary>
            /// Posted Date.
            /// </summary>
            public DateTime PostedDate
            {
                get
                {
                    return mInstance.PostedDate;
                }
                set
                {
                    mInstance.PostedDate = value;
                }
            }


            /// <summary>
            /// External Url.
            /// </summary>
            public string ExternalUrl
            {
                get
                {
                    return mInstance.ExternalUrl;
                }
                set
                {
                    mInstance.ExternalUrl = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// CTAs and other widgets that are to appear in the left widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> LeftWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("LeftWidgetZone");
                }
            }


            /// <summary>
            /// CTAs and other widgets that are to appear in the right widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> RightWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("RightWidgetZone");
                }
            }


            /// <summary>
            /// CTAs and other widgets that are to appear in the bottom widget zone, if the template of the page supports it.
            /// </summary>
            public IEnumerable<TreeNode> BottomWidgetZone
            {
                get
                {
                    return mInstance.GetRelatedDocuments("BottomWidgetZone");
                }
            }


            /// <summary>
            /// When enabled, prevent site visitors from navigating to the page directly.
            /// If the page has any URLs associated with it, they will be removed.
            /// </summary>
            public bool DocumentMenuItemHideInNavigation
            {
                get
                {
                    return mInstance.DocumentMenuItemHideInNavigation1;
                }
                set
                {
                    mInstance.DocumentMenuItemHideInNavigation1 = value;
                }
            }


            /// <summary>
            /// Name of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultController
            {
                get
                {
                    return mInstance.DefaultController;
                }
                set
                {
                    mInstance.DefaultController = value;
                }
            }


            /// <summary>
            /// Name of the action method of the MVC Controller code class that should be responsible for rendering this page on the front-end.
            /// </summary>
            public string DefaultAction
            {
                get
                {
                    return mInstance.DefaultAction;
                }
                set
                {
                    mInstance.DefaultAction = value;
                }
            }

        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_Job" /> class.
        /// </summary>
        public PageType_Job() : base(CLASS_NAME)
        {
            mFields = new PageType_JobFields(this);
        }

        #endregion
    }
}
