//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;

using CMS;
using OslerAlumni.Core.Kentico.Models;
using OslerAlumni.Mvc.Core.Definitions;
using OslerAlumni.Mvc.Core.Kentico.Models;
using OslerAlumni.Mvc.Core.Extensions;

[assembly: RegisterDocumentType(PageType_Job.CLASS_NAME, typeof(PageType_Job))]

namespace OslerAlumni.Mvc.Core.Kentico.Models
{
    /// <summary>
    /// Represents a content item of type PageType_Job.
    /// </summary>
    public partial class PageType_Job :  IBasePageType
    {
        public JobClassification JobClassificationEnum
        {
            get
            {
                JobClassification result;

                return Enum.TryParse(JobClassification, out result)
                    ? result
                    : Definitions.JobClassification.Osler;
            }
        }

        public string JobClassificationDisplay => 
            ((Enum)JobClassificationEnum).GetLocalizedDisplayName();
    }
}
