//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using OslerAlumni.Mvc.Core.Definitions;
using OslerAlumni.Mvc.Core.Extensions;
using OslerAlumni.Mvc.Core.Kentico.Models.Forms;

[assembly: RegisterBizForm(ContactUsItem.CLASS_NAME, typeof(ContactUsItem))]

namespace OslerAlumni.Mvc.Core.Kentico.Models.Forms
{

    /// <summary>
    /// Represents a content item of type ContactUsItem.
    /// </summary>
    public partial class ContactUsItem : IContactUsFormItem
    {
        public int? ContactUsId
        {
            get { return this.ItemID; }
            set { this.ItemID = value.Value; }
        }

        /// <summary>
        /// UserGuid.
        /// </summary>
        [DatabaseField]
        public Guid? UserGuid
        {
            get
            {
                Guid userGuid;

                if (Guid.TryParse(ValidationHelper.GetString($"{nameof(UserGuid)}", string.Empty), out userGuid))
                {
                    return userGuid;
                }

                return null;
            }
            set { SetValue($"{nameof(UserGuid)}", value); }
        }

        public ReasonForContactingUs ReasonForContactingUsEnum
        {
            get
            {
                return ReasonForContactingUs.ToEnum<ReasonForContactingUs>();
            }
            set
            {
                ReasonForContactingUs = value.ToStringRepresentation();
            }
        }

        public string ReasonForContactingUsDisplay
            => ReasonForContactingUsEnum.GetLocalizedDisplayName();

        public string OpportunityTypeDisplay =>
            (OpportunityType.ToEnum<ContactUsOpportunityTypes>()).GetLocalizedDisplayName();
    }
}

